### ISSUE TITLE
Search APIs bug stops build and new blog posts from publishing?

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/theodolite#107] opened 2015-02-20 07:09 UTC
Hi @pezholio @Floppy we published the confidence blog post, we get no issues when merging but the blog post does not come out in the article lists. But if you look in Travis you see something breaks the build that takes place just after the merge. We tried twice, e.g. https://travis-ci.org/OpenAddressesUK/theodolite/builds/51425717 . 

Can you please take a look?

FYI @peterkwells

**Comment by pezholio** [comment] 2015-02-20 07:28
There's a flickering test failure. I've restarted the build and it works now. If this happens again, you can restart the build (assuming you're logged into Travis), by clicking the rebuild button as below:

![travis ci - free hosted continuous integration platform for the open source community](https://cloud.githubusercontent.com/assets/109774/6282779/fd21c276-b8d1-11e4-9c89-535c83cbedfc.png)

It would be nice to put some time in to get this fixed in the next sprint. Shouldn't be too hard. The issue is because sometimes tokens can look like postcodes.

**Closed by pezholio** 2015-02-20 07:28 UTC
Labels: bug
